---
# tasks file for init_server
- name: 修改dns 文件
  copy: 
    src: resolv-{{ env }}.conf
    dest: /etc/resolv.conf 
    owner: root
    group: root
    mode: 0644

- name: 修改 hard限制
  pam_limits:
    domain: '*'
    limit_type: hard
    limit_item: nofile
    value: 65535


- name: 修改 soft限制
  pam_limits:
    domain: '*'
    limit_type: soft
    limit_item: nofile
    value: 65535

- name: 安装基础软件
  yum: 
     #name: ['ntp', 'gcc', 'unzip', 'wget', 'vim','libffi-devel','python-devel','openssl-devel' ]
     name: 
     - ntp
     - gcc
     - unzip
     - wget
     - vim
     - libffi-devel
     - python-devel
     - openssl-devel 
     state: present 

- name: 创建相关目录
  file:
    path: '/data/{{item}}'
    state: directory
    mode: 0755
  loop:
    - packages
    - scripts


- debug:
   msg: '{{user}} {{passwd}}'

- name: 新建用户
  user:
    name: '{{ user }}'
    password: '{{ passwd }}'
    state: present    

- name: sudoers 修改sudo文件
  blockinfile: 
    path: /etc/sudoers
    block: |
      {{user}} ALL=(ALL) NOPASSWD:ALL
    marker: "#{mark} add {{user}} in /etc/sudoers"  
    state: present
    
- name: 修改ssh端口
    

